---
title: "Gasbarro Capstone Project: Gapminder"
output:
  md_document: default
  ioslides_presentation: default
  pdf_document: default
  slidy_presentation: default
  word_document: default
  html_document: default
date: "December 23, 2018"
params:
  symbol: Not Applicable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

library(gapminder)
#library(dplyr)
gapminder

gapminder %>%
  filter(year == 2007, country == "United States")

gapminder %>%
  filter(year==2007) %>% 
  arrange(desc(gdpPercap))

gapminder %>%
  mutate(gdp = gdpPercap * pop) %>%
    filter(year==2007) %>%
    arrange(desc(gdp))

```

```{r echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
library(ggplot2)

gapminder_1952 <- gapminder %>%
  filter(year == 1952)

gapminder_2007 <- gapminder %>%
  filter(year == 2007)

# Change to put pop on the x-axis and gdpPercap on the y-axis
ggplot(gapminder_2007, aes(x = gdpPercap, y = lifeExp, size=pop)) +
  geom_point() +
  scale_x_log10() +
  facet_wrap(~ continent)

gapminder %>% summarize(meanLifeExp = mean(lifeExp))

gapminder %>%
  filter(year == 2007) %>%
  summarize(meanLifeExp = mean(lifeExp))

gapminder %>%
  filter(year == 2007) %>%
  summarize(meanLifeExp = mean(lifeExp),
            totalPop = sum(pop))


# Group By
gapminder %>%
  group_by(year) %>%
  summarize(meanLifeExp = mean(lifeExp),
            totalPop = sum(pop))

gapminder %>%
  filter(year == 2007) %>%
  group_by(continent) %>%
  summarize(meanLifeExp = mean(lifeExp),
            totalPop = sum(pop))

gapminder %>%
  group_by(year, continent) %>%
  summarize(totalPop = sum(pop),
            meanLifeExp = mean(lifeExp)) %>%
  ggplot(., aes(x = year, y = meanLifeExp, color=continent)) +
  geom_line()


by_year <- gapminder %>%
  group_by(year) %>%
  summarize(totalPop = sum(pop),
            meanLifeExp = mean(lifeExp))

by_year

ggplot(by_year, aes(x = year, y = totalPop)) +
  geom_point() +
  expand_limits(y = 0)

gapminder_all <- gapminder

by_year_all <- gapminder_all %>%
  group_by(year) %>%
  summarize(totalPop = sum(pop),
            meanLifeExp = mean(lifeExp))

by_year_all

# Summarize medianGdpPercap within each continent within each year: by_year_continent
by_year_continent <- gapminder %>%
  group_by(year, continent) %>%
  summarize(medianGdpPercap=median(gdpPercap))

# Plot the change in medianGdpPercap in each continent over time
ggplot(by_year_continent, aes(x = year, y = medianGdpPercap, color=continent)) +
  geom_point() +
  expand_limits(y = 0)

# Summarize the median GDP and median life expectancy per continent in 2007
by_continent_2007 <- gapminder %>%
  filter(year==2007) %>%
  group_by(continent) %>%
  summarize(medianLifeExp=median(lifeExp), medianGdpPercap=median(gdpPercap))

# Use a scatter plot to compare the median GDP and median life expectancy
ggplot(by_continent_2007, aes(x = medianGdpPercap, y = medianLifeExp, color=continent)) +
  geom_point()
```


```{r echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
gapminder_all %>% 
  filter(continent=="Africa",year>=2002) %>% 
  summarize(totalPop=sum(pop))

# Summarize the median gdpPercap by year, then save it as by_year
by_year <- gapminder %>%
  group_by(year) %>%
  summarize(medianGdpPercap=median(gdpPercap))

# Create a line plot showing the change in medianGdpPercap over time
ggplot(by_year, aes(x = year, y = medianGdpPercap)) +
  geom_line() +
  expand_limits(y = 0)

# Summarize the median gdpPercap by year & continent, save as by_year_continent
by_year_continent <- gapminder %>%
  group_by(year, continent) %>%
  summarize(medianGdpPercap=median(gdpPercap))

# Create a line plot showing the change in medianGdpPercap by continent over time
ggplot(by_year_continent, aes(x = year, y = medianGdpPercap, color=continent)) +
  geom_line() +
  expand_limits(y = 0)


# Summarize the median gdpPercap by year and continent in 1952
by_continent <- gapminder %>%
  filter(year==1952) %>% 
  group_by(continent) %>%
  summarize(medianGdpPercap=median(gdpPercap))

# Create a bar plot showing medianGdp by continent
ggplot(by_continent, aes(x = continent, y = medianGdpPercap)) +
  geom_col()

# Filter for observations in the Oceania continent in 1952
oceania_1952 <- gapminder %>%
  filter(year==1952, continent=="Oceania")

# Create a bar plot of gdpPercap by country
ggplot(oceania_1952, aes(x = country, y = gdpPercap)) +
  geom_col()

# Filter for observations in the Oceania continent in 1952
oceania_1952 <- gapminder %>%
  filter(year==1952, continent=="Oceania")

# Create a bar plot of gdpPercap by country
ggplot(oceania_1952, aes(x = country, y = gdpPercap)) +
  geom_col()

ggplot(gapminder_2007, aes(x = lifeExp)) +
  geom_histogram(binwidth = 5)

ggplot(gapminder_1952, aes(x = pop)) +
  geom_histogram() +
  scale_x_log10()

ggplot(gapminder_2007, aes(x = continent, y = lifeExp)) +
  geom_boxplot()

gapminder_1952 <- gapminder %>%
  filter(year == 1952)

# Create a boxplot comparing gdpPercap among continents
ggplot(gapminder_1952, aes(x = continent, y = gdpPercap)) +
  geom_boxplot() +
  scale_y_log10()

# Add a title to this graph: "Comparing GDP per capita across continents"
ggplot(gapminder_1952, aes(x = continent, y = gdpPercap)) +
  geom_boxplot() +
  scale_y_log10() +
  ggtitle("Comparing GDP per capita across continents")


```